#!/usr/bin/env bash




##
## ## Desktop Background Image
##

#hyprpaper &
#[ -x "${HOME}/.azotebg" ] && "${HOME}/.azotebg" &
#wf-background &
#pcmanfm-qt --desktop --daemon-mode &




##
## ## Polkit
##

/usr/libexec/xfce-polkit &




##
## ## panel / waybar
##

#waybar &




##
## ## panel / wf-shell
##

#wf-panel &




##
## ## nm-applet
##

nm-applet &




##
## ## fcitx5
##

fcitx5 &
